---
exclude_paths:
  - "client/build/**"
  - "client/coverage/**"
  - "client/.nyc_output/**"
  - "coverage-merged/**"
  - "lighthouse-results/**"
  - "client/.angular/**"
  - "client/node_modules/**"
  - "client/public/**"
  - "client/src/assets/**"
  - "client/*.config.*"
  - "backend/build/**"
  - "backend/tests/**"
  - "client/cypress/**"
  - "client/scripts/**"
  - ".github/**"
  - "run.sh"
  - "**/*.md"
  - "**/*.sh"
  - "**/*.yml"
  - "**/*.yaml"
  - "**/*.json"
  - "**/*.map"
  - "**/eslint.config.js"

engines:
  metric:
    config:
      languages:
        - "python"
        - "typescript"
        - "javascript"
  duplication:
    exclude_paths:
      - "client/build/**"
      - "client/coverage/**"
      - "client/.nyc_output/**"
      - "coverage-merged/**"
      - "lighthouse-results/**"
      - "client/.angular/**"
      - "client/node_modules/**"
      - "client/public/**"
      - "client/src/assets/**"
      - "client/*.config.*"
      - "backend/build/**"
      - "backend/tests/**"
      - "client/cypress/**"
      - "client/scripts/**"
      - ".github/**"
      - "run.sh"
          - "**/eslint.config.js"
